### ISSUE TITLE
Add a flag on lotus-miner architecture

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/lotus-docs#113]
Based on https://filecoinproject.slack.com/archives/CQLDFHAJY/p1646639236183139 we need to add the a flag that hardware used in the docs is older and should not be bought as it is. This is just an example hardware.

**Comment by rjan90** [comment]
I think removing it and maybe just posting a link to the[ community hardware ](https://github.com/filecoin-project/lotus/discussions/6071) is a good start. Maybe even post Benjamins YouTube-video about Filecoin for Solo-miners, as that gives a good into to what kind of hardware is needed: [https://youtu.be/LKMjCgo-fkA](https://youtu.be/LKMjCgo-fkA)
