### ISSUE TITLE
Lotus configuration is missing `RemoteBackend` docs for connecting a remote wallet.

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus-docs#180]
this thread: https://filecoinproject.slack.com/archives/CEHHJNJS3/p1626341135112400

[Wallet]
   RemoteBackend = "*"
  #EnableLedger = false
  #DisableLocal = false

seem to be undocumented. see

https://github.com/filecoin-project/lotus/blob/master/cmd/lotus-wallet/main.go#L63

**Comment by rjan90** [comment]
Closing since a tutorial for running a remote `lotus-wallet` which uses the RemoteBackend is available now.
