### ISSUE TITLE
Instruct reader what happens after "Compacting the chain".

### ISSUE THREAD

**Issue by cyberience** [filecoin-project/lotus-docs#183]
**URL of the page in question:**
https://docs.filecoin.io/get-started/lotus/chain/#compacting-the-chain-data

**What's wrong with this page?**
It doesnt say what next, or what to expect. For example, when do I stop the daemon to start the systemctl service, or does this run continue after the import? Most new users suffer from a lack of knowing what to expect for a correct running system, wasting much time in trial and error.

**Comment by rjan90** [comment]
Closing this Doc request since Lotus defaults to SplitStore which automatically compacts the chain for the user.
