### ISSUE TITLE
Command to download lightweight snapshot for chain sync does not work

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/lotus-docs#189]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs.filecoin.io/get-started/lotus/chain/#lightweight-snapshot

**What's wrong with this page?**
Running the provided command `curl -sI https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car | perl -ne '/x-amz-website-redirect-location:\s(.+)\.car/ && print "$1.sha256sum\n$1.car"' | xargs wget` results in an error. (The click to download option seems to be working fine.)

![Screen Shot 2021-06-17 at 10 20 18 AM](https://user-images.githubusercontent.com/2343218/122444658-a148ba80-cf55-11eb-9959-a4e89b83dd66.png)

**What would you like to have changed/amended/fixed in order to make things right?**
We should fix the command to actually point to a downloadable chain snapshot.

**Would you be interested in helping fix this page?**
I don't know how we gather and save snapshots :(

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by rjan90** [comment]
Closing this issue now, since the command works fine! 😄 Thanks for the issue report
