### ISSUE TITLE
Mirror documentation between the `lotus` and `lotus-docs` repos.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/lotus-docs#19]
Now that lotu.sh has been revamped, we need to take a look at how to handle automation between the `filecoin-project/lotus` and `filecoin-project/lotus-docs` repos.

The Lotus engineers found adding documentation into the `documentation` folder within the `filecoin-project/lotus` repo incredibly easy, and didn't break their _flow_. Having one repo that contains docs and code was super useful for them. However, to build the lotu.sh site, markdown content needs to live in the `content` folder of the `filecoin-project/lotus-docs` repo.

Let's use this issue to discuss how we can effectively _mirror_ content between the `lotus/docuentation` folder and lotus-docs/content` folder. Again, these two folders live in two different repos.

Here are two solutions I've thought of so far:

## Move this repo into `filecoin-project/lotus`

This will keep everything related to Lotus in once place. But there are some obvious drawbacks to this. Firstly, this will massively increase the number of files within the Lotus repo. Also, it means that Fleek will have to grab the whole `filecoin-project/lotus` repo every time it has to build the site. It also means that developers/writers have to jump down a whole lot of folders just to get to the content section

On the other hand, it does mean that we don't have to deal with submodules.

## Split `filecoin-project/lotus-docs` into two repos

The idea here is to split _this_ repo into two:

- `filecoin-project/lotus-docs`: contains everything within the `/content/en/docs` folder.
- `filecoin-project/lotus-docs-website`: contains just the build scripts and Hugo stuff.

Then we would add the `filecoin-project/lotus-docs` as a _submodule_ into both `filecoin-project/lotus-docs-website` and `filecoin-project/lotus:documentation`.

The main issue with this is that developers/writers/Fleek now have to deal with submodules, which can be finicky.

**Comment by arajasek** [comment]
Of the options, I'd vote for `Split filecoin-project/lotus-docs into two repos`. Most of the Lotus engineers themselves are fine with submodules, and other contributors who aren't can benefit from the education ;)

I'm not really clear why `lotus-docs` has to be its own repo (and then submoduled into `lotus-docs-website`), instead of `lotus-docs-website` just grabbing the code in the `documentation` folder of Lotus directly? But I'm not too fussed about it.

**Comment by johnnymatthews** [comment]
> I'm not really clear why lotus-docs has to be its own repo

Maybe it doesn't have to be. Having it as it's own repo follows the _nucleation_ ideal, but it's strictly necessary. The only problem with having the docs sit in the `documentation` folder in `filecoin-project/lotus` is that it might be tricky to tell Fleek.co what to do.

**Comment by jimmylee** [comment]
What we did before...

- Using the GitHub V3 API to query the markdown files in the repository (whatever is on master/main).
- The documentation could live in the Lotus repository and be the single source of truth.
- The previous documentation website was just a renderer that would interpret the plain text string for the markdown file in the lotus repository.
