### ISSUE TITLE
Tell users how to find the latest tag, and grab that from GitHub, instead of using the `master` branch.

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus-docs#190]
with the new branch system for lotus we see a fair amount of miners checking out master instead of the latest release tag.

is there a way to dynamically pull the latest stable release tag from filecoin-project/lotus and replace the <x.x.x> with it in the build instructions?

having people on 1.11-dev instead of 1.9.0 is causing possible problems for them and the questions in slack are always answered the same way: downgrade to the latest stable release and see if the problem persists.

**Comment by rjan90** [comment]
https://github.com/filecoin-project/lotus-docs/pull/346 Changes all the `git checkout <tag_or_release>` to `git checkout releases` which always checks out the latest stable releas throughout the documentation. In the comments it is noted that if one needs a specific release, you should use `git checkout <tag_or_release>`.
