### ISSUE TITLE
Use GPU for ffi

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus-docs#192]
for lotus v1.9.2 and below, miners should set `FFI_USE_GPU2=1 FFI_BUILD_FROM_SOURCE=1` or  `FFI_USE_GPU=1 FFI_BUILD_FROM_SOURCE=1` before building lotus to enable using GPU for ffi.

I think the note should be add in this section https://docs.filecoin.io/mine/lotus/miner-setup/#performance-tweaks

**Comment by rjan90** [comment]
Closing this issue since its outdated! That `FFI_BUILD_FROM_SOURCE=1` should be used, is also clearly defined in the `lotus-miner` setup section now 😄
