### ISSUE TITLE
Clearly define how many tasks a Lotus Worker can perform at once.

### ISSUE THREAD

**Issue by shengzhou1216** [filecoin-project/lotus-docs#196]
**URL of the page in question:**
https://docs.filecoin.io/mine/lotus/seal-workers/#resource-allocation-in-workers

**What's wrong with this page?**
In the first line of **[Resource allocation in workers]** section, it's said that "Each Lotus Worker will run at most two tasks". Maybe there is no limit to the maximum number of tasks that each worker can execute at the same time, because I have tried to execute more than 2 PC1 tasks at the same time with one worker.

**What would you like to have changed/amended/fixed in order to make things right?**
There is no limit to the number of tasks that each Lotus Worker can perform, it only depends on your hardware resources.

**Comment by rjan90** [comment]
Hey! Thanks for the issue-ticket. Closing this now, since the `seal-worker` has been updated to reflect that there is no limit to how many tasks a lotus-worker can perform, it only depends on the hardware.

Again, thanks for the issue-ticker 😄
