### ISSUE TITLE
Explain what happens to a client's data when a miner is punished for poor reliability.

### ISSUE THREAD

**Issue by dacoach01** [filecoin-project/lotus-docs#197]
**URL of the page in question:**
https://docs.filecoin.io/about-filecoin/why-filecoin/

**What's wrong with this page?**
This page explains nicely how the miners responsibilities are established and incentivized for reliability, and punished for poor reliability, but it doesn't explain what happens to the contents of the stored data if said miner acts irresponsibly and loses the content they store.  How is the consumer of the storage affected?

**What would you like to have changed/amended/fixed in order to make things right?**
Explain if there is redundancy of data distributed in the "swarm" of retrieving class or the storing class.  If joe blow network participant just shuts down, where does the data go from that node?  How is it retrieved if lost or destroyed?

**Would you be interested in helping fix this page?**
No. Just trying to learn and not getting some basic info from the site.

**Is there any other feedback you'd like to share about Filecoin docs?**
No.

**Comment by rjan90** [comment]
Closing ticket as outdated.
