### ISSUE TITLE
Explain how to set the fee in the daemon config file so the CreateMiner msg doesn't get stuck in the mpool 

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus-docs#201]
The CreateMiner message is the first message that gets stuck when initializing a new miner. Due to the default setting for the (non existent in the default config.toml, might change with 1.4.1??) DefaultMaxFee value

**What's the subject of the item you're requesting?**
This should be in the miner setup flow.

**What's the content of the item you're requesting?**
see the pull request regarding the fee section
https://github.com/filecoin-project/filecoin-docs/pull/623
this applied with correct values to get a CreateMiner Message on chain

**What will the user know how to do after going through this item?**
How to set the daemons config.toml DefaultMaxFee so the CreateMiner message deasn;t get stuck

**Would you be interested in helping create this item?**
sure. ping me

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
This is reflected in the [docs](https://lotus.filecoin.io). Closing.
