### ISSUE TITLE
[DOCS ISSUE] Page: Lotus: chain management

### ISSUE THREAD

**Issue by shawnp0wers** [filecoin-project/lotus-docs#203]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
_https://docs.filecoin.io/get-started/lotus/chain/#restoring-a-custom-snapshot_

**What's wrong with this page?**
The order is wrong with the options for halting after importing the chain. 

**What would you like to have changed/amended/fixed in order to make things right?**
Change the example to:
`lotus daemon --halt-after-import --import-snapshot <filename>`
(it currently has --halt-after-import and --import-snapshot in the wrong order)

**Would you be interested in helping fix this page?**
I don't know how yet, sorry. Eventually I'll figure it out. :) 

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by rjan90** [comment]
Closing this a the proper command is displayed in the lotus-docs: https://lotus.filecoin.io/lotus/manage/chain-management/#restoring-a-custom-snapshot
