### ISSUE TITLE
Miner config and commands section.

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus-docs#211]
There's always docs work to be done, but we especially want them for the recently-added features that will be tested in incentivised testnet:

- CC configs
- Deal acceptance / rejection config
- Packing deals in a sector config

Some descriptive content about what CC is, what fast retrieval is, etc. would be good too

**Comment by rjan90** [comment]
Closing this issue as outdated. We now have a `advanced configuration` in the storage provider section which covers the configs of the different sub-systems!
