### ISSUE TITLE
Explain how to download the latest Calibnet snapshot.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/lotus-docs#224]
How to get the latest calibnet snapshot.

1. Go to this Gist: https://gist.github.com/openworklabbot/
1. Grab the CID from the top.
1. Go to `https://dev.node.glif.io/calibrationapi/ipfs/8080/ipfs/<CID>` and replace `<CID>` with the CID you got in step 2. This link should download the latest Calibnet snapshot (last 900 blocks).

**Comment by rjan90** [comment]
Documentation for the downloading Calibration snapshot is here: https://lotus.filecoin.io/lotus/manage/chain-management/#lightweight-snapshot
