### ISSUE TITLE
Build > Getting Started > Connect to a hosted node

### ISSUE THREAD

**Issue by brunolm** [filecoin-project/lotus-docs#23]
**What's the subject of the item you're requesting?**
Connect to a hosted node

**What's the content of the item you're requesting?**
How to connect to a hosted node

**What will the user know how to do after going through this item?**
Connect to a hosted node

**Would you be interested in helping create this item?**
I'd like to brainstorm with other contributors and work in collaboration to create this content

**Is there any other feedback you'd like to share about Filecoin docs?**
\-

**Comment by longfeiWan9** [comment]
@johnnymatthews I have looked through the docs we currently have and also thought about what exactly this issue means. I think [Build/get-started](https://docs.filecoin.io/build/get-started/) might already cover what this issue describes. 

So basically, the hosted nodes options are:
+ Infura
+ Glif Node
+ api.chain.love
+ host a lotus full node by developers themselves.

[Build/get-started](https://docs.filecoin.io/build/get-started/) takes Infura as example of hosted nodes. I think hosted node like Infura & Glif provides pretty much similar read-only functions like querying chain data. So I think this `build/get-started` docs already covers how to connect to the hosted node (Infura or Glif node) and use its service, what do you think?

What's more, we can add to this tutorial is that using signing libraries or other library to achieve: 
+ Manage Wallet & FIL by sending signed transactions to `MPoolPush()`

Let me know what you think ? Thank you

**Comment by johnnymatthews** [comment]
> Build/get-started might already cover what this issue describes.

That's a good point! I wrote that tutorial a _while_ ago though, so it might need updating. Would you be able to tackle that?

> What's more, we can add to this tutorial is that using signing libraries or other library to achieve:

That sounds like a good idea!

**Comment by longfeiWan9** [comment]
@johnnymatthews sure, then I think what I will do is:
1. make sure the `build/get-started` is up-to-date.
2. Drafting the tutorials to use signing libraries or other library to achieve wallet management with hosted node.

**Comment by johnnymatthews** [comment]
Closed in https://github.com/filecoin-project/lotus-docs/pull/231
