### ISSUE TITLE
Update Lotus getting started to reflect changes to Fil+ Miner Registry.

### ISSUE THREAD

**Issue by terichadbourne** [filecoin-project/lotus-docs#26]
Per @dkkapur, the Fil+ Miner Registry has been updated to show more useful info that will prevent users from having to visit multiple websites when selecting a storage provider.  🎉

![image](https://user-images.githubusercontent.com/19171465/127697448-d7ece02f-b794-4755-9e32-5b5f4853b5be.png)

Deep, do you still have further changes you're planning to make that would affect how we instruct users to take advantage of it? When you're done with changes on your end, I think we should revisit the whole section of the Getting Started FFF tutorial that addresses how pick a storage provider to make a Fil+ free deal with. 

- [ ] Update FIl+ Miner Registry screenshot
- [ ] Update Fil+ Miner Registry instructions
- [ ] See if we can remove the Filfox.io section if we've confirmed that the Fil+ Miner Registry now offers access to all the needed details in a single site. 
- [ ] Scan for other relevant edits needed, refernces to Fil+ Miner Registry elsewhere in docs that might need updating

**Comment by johnnymatthews** [comment]
I'm guessing this got closed in #25 @longfeiWan9 ?
