### ISSUE TITLE
Add space between bottom of callout box and next element.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/lotus-docs#277]
There needs to be a tiny bit of padding/margin between the bottom of a callout and the next element:

<img width="775" alt="Screen Shot 2022-06-08 at 12 05 02 PM" src="https://user-images.githubusercontent.com/9611008/172664569-62dc75d7-b6c4-4d6c-91bd-382e8b9643ea.png">

Padding similar to what's above the callout element is probably fine.

**Comment by TMoMoreau** [comment]
Closing this as completed, PR has been merged.
