### ISSUE TITLE
Tons of broken top-level links

### ISSUE THREAD

**Issue by momack2** [filecoin-project/lotus-docs#28]
top links clickable from https://docs.filecoin.io/

- https://docs.filecoin.io/mine/
- https://docs.filecoin.io/store/slate
- https://docs.filecoin.io/mine/how-mining-works
- https://docs.filecoin.io/mine/mining-architectures
- https://docs.filecoin.io/mine/hardware-requirements

**Comment by johnnymatthews** [comment]
Fixed in https://github.com/filecoin-project/filecoin-docs/pull/1117
