### ISSUE TITLE
Document new lotus feature, multisig cancel command.

### ISSUE THREAD

**Issue by SgtCoin** [filecoin-project/lotus-docs#33]
Lotus introduced a new cancel command for multisig proposals. we need to import the documentation for this new process. 

https://github.com/filecoin-project/lotus/pull/7645/files

**Comment by johnnymatthews** [comment]
## Tasks

- [ ] Import docs from lotus repo: https://github.com/filecoin-project/lotus/pull/7645/files?file-filters%5B%5D=.md&show-viewed-files=true#diff-f6709abd6784db12b8b785ae67e58cc98486a3a348e0351c6b81de68fd3f3e5dR2704-R2740
- [ ] Add content into https://lotus.filecoin.io/docs/apis/json-rpc/#msigcancel

**Comment by rjan90** [comment]
Closing this issue as the `msig cancel` command has been documented.
