### ISSUE TITLE
Document new lotus feature, message param inspection

### ISSUE THREAD

**Issue by SgtCoin** [filecoin-project/lotus-docs#34]
Lotus introduced a new feature to inspect messages, specifically adding a new section to cover the params of the message. 

https://github.com/filecoin-project/lotus/pull/7639/files

We need to document this.

**Comment by johnnymatthews** [comment]
Is there any existing docs content for this feature? If not, we'll need one of the Lotus dev team to draft:

- The problem this feature solves.
- How it solves the problem.
- How users can use this feature.
