### ISSUE TITLE
Audit and revise Lotus section

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus-docs#360]
The Lotus section struggles with some complexity and structural issues that lead to the same questions and issues later on. Usually, these questions and issues are from users new to Lotus - and their main goal is often to install Lotus, set up, and sync the main chain.

The Techincal Support Engineers @ Lotus had a thinking session where we went through the current structure of the Lotus-section, and came up with a couple of ideas to address these issues. Similar to the audit of the Storage Provider section we aim to have a more top to bottom approach, where the first sub-sections should help potential users to install, set up, and sync a node without being presented with too many options or configurations. Later on, we can rather introduce them to concepts such as changing networks, chain management/SplitStore, multi-sig, etc.

**Proposed structure:**
```
├─ Get Started /
│  ├─ What is Lotus 
│  ├─ Networks
│  ├─ Types of nodes
├─ Setup/
│  ├─ Prerequisites
│  ├─ Linux
│  ├─ MacOS
│  ├─ Cloud Services
│  ├─ Start Lotus
├─ Manage/
│  ├─ Chain Management
│  ├─ Switch Networks
│  ├─ Manage FIL
│  ├─ Message pool
│  ├─ Ledger
│  ├─ Multisig
│  ├─ Backup and restore
│  ├─ CLI
├─ Advanced Configurations/
│  ├─ Advanced Configuration
│  ├─ SplitStore
├─ Developers/
│  ├─ Glif Nodes
│  ├─ Local network
│  ├─ Local Network FIL+
│  ├─ Bootstrap
│  ├─ Contribute
```

**Main points for each subsection:**

- Get started
   - Architechturally the pages in this section looks fairly good as an entry point as is today, and would mostly just need an audit of the content.
   - Add typical user groups under each node type in the "Types of node" page. A video could also be beneficial to bring clarity to what the differences are.
   
- Setup
   - Changing title of the section from install to setup. This is where we take the user from install to starting and syncing Lotus. This section should guide the user in a quite strict fashion, with not too many configuration options presented, and show the user how one can sync the main chain via a lightweight snapshot.
   - Seperate out `Start the Lotus daemon and sync the chain/Interact with the daemon/Stop the Lotus daemon` that are in each of the supported plattform install pages to its own page. The `Start Lotus` page should also highlight the most basic configs (like connectivity and the ability to set a desired LOTUS_PATH)
   
- Manage
   - This section should be moved above the Advanced Configurations section (previously Configure)
   - Remove the Troubleshooting page, add all missing tips and tricks in here as content in the Knowledge Base.
   - Add a seperate page about using Ledger.
   - Move the SplitStore content out to a seperate page under Advanced Configurations.
   
- Advanced Configurations
   - Similar to the Storage Provider section, this section contains configurations that experienced Lotus users would like to check out.
   - SplitStore should have it´s own page under this section.

- Developers
   - Mostly fine as is. Will move the contribute page from the previously Project-section, into this section.
   
This is just outlining what each section should go through on a broad level, a lot of the content in each page will probably need some revising.

**Comment by rjan90** [comment]
Current plan is to audit and revise this section of the docs along with many of our other ongoing work items, so we schedule to use approximately 1 week per section, with a total estimate of 5 weeks. 
> This is a draft plan -- it is subject to change and refinement as we move along.

**Get Started:**
- [ ] Audit and revise "What is Lotus"
- [ ] Audit and revise "Networks"
- [ ] Audit and revise "Types of nodes"

**Setup**
- [ ] Rename section to Setup (previously Install):
- [ ] Audit and revise "Prerequisities"
- [ ] Seperate out the "Start the Lotus daemon and sync the chain/Interact with the daemon/Stop the Lotus daemon" content to its own page "Start Lotus"
- [ ] Audit and revise "Linux"
- [ ] Audit and revise "MacOS"
- [ ] Audit and revise "Cloud Services"

**Manage**
- [ ] Change weight to move section above Advanced Configurations (previously Configure)
- [ ] Move all missing tips and tricks in Troubleshooting to the Knowledge base
- [ ] Depreciate the Troubleshooting page
- [ ] Audit and revise "Chain Management"
- [ ] Audit and revise "Switch Networks"
- [ ] Create seperate page for "Ledger"
- [ ] Audit and revise "Manage FIL"
- [ ] Audit and revise "Message pool"
- [ ] Audit and revise "Multisig"
- [ ] Audit and revise "Backup and restore"
- [ ] Audit and revise "CLI"

**Advanced Configurations**
- [ ] Rename section to Advanced Configurations (previously Configure):
- [ ] Add SplitStore content as a seperate page under Advanced Configurations.
- [ ] Move "Bootstrap" page to the Deveoplers section
- [ ] Depreciate "Nodes in China" page
- [ ] Rename "Defaults" to "Advanced Configurations" and audit and revise

**Developers**
- [ ] Audit and revise "Glif Nodes"
- [ ] Audit and revise "Local network"
- [ ] Audit and revise "Bootstrap"
- [ ] Move "Contribute" page into Developers section and audit and revise
- [ ] Depreciate Project section

**Comment by rjan90** [comment]
An addition to this audit, we also plan to audit the Tutorial-section of the docs. Agenda here is:

**Lotus section:**
- [ ] Audit and revise "Setup" tutorial
- [ ] Audit and revise "Store data" tutorial
- [ ] Audit and revise "Retrieve data" tutorial
- [ ] Audit and revise "Import data from IPFS" tutorial
- [ ] Audit and revise "Large Files" tutorial
- [ ] Audit and revise "Payment Channels" tutorial
- [ ] Audit and revise "Building with Lotus API" tutorial
- [ ] Audit and revise "Run a Disputer" tutorial
- [ ] Audit and revise "Remote lotus-wallet management" tutorial

**Storage Provider section**
- [ ] Audit and revise "Lotus Miner setup" tutorial
- [ ] Audit and revise "Add Seal Worker" tutorial
- [ ] Audit and revise "Cuda setup" tutorial
- [ ] Audit and revise "Multisignature as a owner address" tutorial

**Comment by smagdali** [comment]
I've been doing a fair bit of work over the past few months on user testing the lotus tutorials (both here and on docs.) with launchpad cohorts attendees- I've ported some of that learning into the lotus section itself. Very keen to chat before anyone makes large changes to them - we're still finding users having issues with the installation process (not least when[ the builds break](https://github.com/filecoin-project/lotus/issues/9357)). I now have a testing setup for intel and M1 macs, too.

**Comment by rjan90** [comment]
I´m closing this issue/project now, since the audit/revision of the main Lotus-section is now done. I´ll have a lot less bandwidth going forward to work on a audit of the Tutorials-section, so I will that part/agenda should be moved into a new issue/project/sprint for visibilty.
