### ISSUE TITLE
How to identify a good epoch number.

### ISSUE THREAD

**Issue by fadyanwar** [filecoin-project/lotus-docs#42]
On document https://github.com/filecoin-project/lotus-docs/blob/main/content/en/docs/set-up/troubleshooting.md under section "chain linked to block marked previously as bad" it says reset head to a known good epoch number, it doesn't however clarify how to identify such a good epoch.

**Comment by johnnymatthews** [comment]
From PL Slack:

> [...] a reasonable suggestion is to run `lotus chain list --count=X` to get some large number `X` of tipsets, and see if there's a sudden change in tipset size and density. You're looking for a point when the number of `null` tipsets increases and / or the number of blocks per tipset falls from ~5 to (say) 1 [...]
