### ISSUE TITLE
Docs link expired 

### ISSUE THREAD

**Issue by kaushikc44** [filecoin-project/lotus-docs#442]
![image](https://user-images.githubusercontent.com/59849731/204505977-aa1e45c9-262e-403e-9212-16bf353d7602.png)
Hi , I came across the docs link and it seems that it has expired. Please look into it . Thanks

**Comment by rjan90** [comment]
Hey! Thanks for the report. Where on the Lotus-site did you find the link to that site?

**Comment by kaushikc44** [comment]
It was on file coin site.

**Comment by rjan90** [comment]
Can you take a screenshot of the link that got you to this error?

**Comment by kaushikc44** [comment]
![image](https://user-images.githubusercontent.com/59849731/204510614-7187cfa2-bb7c-46dd-9eea-7e7ced7d6219.png)

"Learn more" link is giving an error in the overview section.

**Comment by johnnymatthews** [comment]
This link seems to work fine on my end now. Closing.
