### ISSUE TITLE
Review Store and Retrieve tutorial.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus-docs#501]
https://lotus.filecoin.io/tutorials/lotus/store-and-retrieve/store-data/

- [ ] make it more simple
- [ ] go through in devnet setting (removing the whole mainnet datacao thing)
- [ ] using boost for client and sp side of data onboarding

**Comment by johnnymatthews** [comment]
While the tutorial could do with updating, it is definitely not the _flow_ that users/developers should be following if they legit wanna store data on Filecoin. There are other, easier processes, for storing stuff that we could point the user to.

**Comment by rjan90** [comment]
Given that the Legacy Markets has been deprecated, and now set to `Draft: True` in https://github.com/filecoin-project/lotus-docs/pull/736, I´m closing this ticket now.
