### ISSUE TITLE
Add docs for msg index

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus-docs#582]
introduced in https://github.com/filecoin-project/lotus/pull/10452

Document the config, usage, expected growth and such.

**Comment by BlocksOnAChain** [comment]
@johnnymatthews hey any updates on this, is it still relevant or we can close it?

**Comment by johnnymatthews** [comment]
PR created here: https://github.com/filecoin-project/lotus-docs/pull/607
