### ISSUE TITLE
Investigate root cause of unusual memory spikes

### ISSUE THREAD

**Issue by GlacierWalrus** [filecoin-project/lotus-docs#611]
Our monitoring history indicates the chain archiver occasionally exhibits memory spikes of up to approximately 30Gb, and very occasionally as high as 70Gb.

The snapshot size seems to be consistent between all sampled processes, so I imagine this memory spike relates to some unbounded operation the archiver is performing.

See the example of the memory profiles vs snapshots which illustrates the problem

![Image](https://github.com/filecoin-project/lotus-docs/assets/114941647/2a0dbcdf-0e5d-4366-a196-c444a3511fc8)

**Comment by GlacierWalrus** [comment]
I don't know how.... but ZH seems to have created this issue in lotus-docs instead of FCA. Sorry about the noise.

**Comment by rjan90** [comment]
> I don't know how.... but ZH seems to have created this issue in lotus-docs instead of FCA. Sorry about the noise.

Haha 😆! No worries
