### ISSUE TITLE
How mining works link leads to a 404

### ISSUE THREAD

**Issue by lalexgap** [filecoin-project/lotus-docs#634]
Currently [the link for How Mining Works](https://github.com/filecoin-project/lotus-docs/blob/9ad9275a9bb8dd02c226d53d471128ab3cf629c5/content/en/storage-providers/get-started/overview/index.md?plain=1#L16) on the lotus readme links to https://docs.filecoin.io/storage-provider/how-providing-works/ which results in a 404.

**Comment by rjan90** [comment]
Hey @lalexgap, thanks for the issue! I have opened a PR fixing it in #635
