### ISSUE TITLE
Create a tutorial for how to backfill messages in Lotus

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus-docs#700]
We need to run create a Tutorial article that walks through how to backfill messages. [We have some notes written down here](https://docs.google.com/document/d/1ggTnWPiUfcmLgtxoggWQpoxkM8v_5KFIsVZMH_BpVbg/edit#heading=h.qdqvflcumzmy) for how to do it. 

We need to re-run those steps and and refine thes steps, and create a tutorial.

**Comment by Stebalien** [comment]
(we should also consider making backfilling automatic)

**Comment by TippyFlitsUK** [comment]
https://github.com/filecoin-project/lotus-docs/pull/701
