### ISSUE TITLE
lotus provider page has vanished, now 404s - can it be restored and updated instead?

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/lotus-docs#757]
I spotted this was now broken I had a link to it from some other docs...

https://lotus.filecoin.io/storage-providers/lotus-provider/setup/ 

Should we restore it, and  update it with something that explains the current state of play (Curio, right?) instead- would be a more helpful developer experience...

Stef

**Comment by rjan90** [comment]
I added a alias, so people clicking that will be redirected to https://lotus.filecoin.io/storage-providers/curio/overview/ at least in: #758

**Comment by LexLuthr** [comment]
@smagdali Can you please let me know which docs redirected here? We should fix the original links to point to Curio docs instead of creating a link chain via Lotus docs.

**Comment by smagdali** [comment]
This one was on an FF internal notion page, so I can fix it. And yup you should avoid chains where possible but you still need them to deal with inbound links from urls you can't update, like old slack messages, blog posts, and external domains.

**Comment by rjan90** [comment]
Users trying to access https://lotus.filecoin.io/storage-providers/lotus-provider/setup/ is now being redirected to https://docs.curiostorage.org, ref: #758
