### ISSUE TITLE
Remove Blog link from top of page.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/lotus-docs#9]
Since we're not sure if the Lotus team actually want a Blog feature or not, we should remove the topbar nav link pointing to the blog, for now. It's super easy to add back in if the team do want to use it.

![image](https://user-images.githubusercontent.com/9611008/138895901-36c1759f-8123-47f5-ab03-6dfea5ea09aa.png)

**Comment by johndmulhausen** [comment]
Done!
