### ISSUE TITLE
Create a Calibnet tutorial for lotus

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/lotus-docs#97]
Write a new tutorial for how run a calibnet miner and a PC1 worker for the said miner

**Comment by LexLuthr** [comment]
Make changes to the tutorials section based on https://github.com/filecoin-project/lotus-docs/pull/82#issuecomment-1069385855

**Comment by Annamarie2019** [comment]
@LexLuther I'm triaging this issue. Does #98, which is merged resolve this issue, so we should close this issue or do we still need to:

"Create a new tutorial for how run a calibnet miner and a PC1 worker for the miner." ? 

(I see some text on calibnet in the Files changed for 98, but I'm not sure that resolves all that's needed.)

**Comment by LexLuthr** [comment]
Yes, this was fixed with #98 and would be merged in #124 
Nothing else is needed on this issue. Once #124 is merged, we can close it out. Me and Johnny are discussing the sub-menu naming. Rest is all done.
